### ISSUE TITLE
Crash after login

### ISSUE THREAD

**Issue by and-sha** [etternagame/etterna#712]
The game crashes after logging in (Game Start > Click to login). On relaunch it chashes after pressing "Game Start", showing song select screen for a brief moment

Crash reports: https://hastebin.com/jobaharinu.makefile (after logging in)
https://hastebin.com/eraleqefej.makefile (on relaunch)
Log: https://hastebin.com/viwafivumi.sql (on relaunch)

Manjaro Linux 18.1.0 x64, kernel version 5.5.4
Etterna built from AUR package, which was modified to build the 0.68.1 version (PKGBUILD file https://hastebin.com/esuseqasuv.bash )
OpenSSL 1.1.1d

Clone of #550 ?

**Comment by izik1** [comment]
Maintainer of that AUR package (updating literally as I'm typing this, noticed the new version about 15 minutes ago), can confirm that has been happening for as long as I can remember... So at least 0.66.x

**Comment by poco0317** [comment]
Try the etterna-git AUR package. Despite the fact that it says it's for 0.65.1 it actually pulls from our repository so should just kind of work.

In either case I feel like that wouldn't solve the actual issue here. But the crash report you give is more informative than it was before 0.68.0 which is at least something to look in to. I wish it had a usable call stack, though.

**Comment by ridho9** [comment]
https://pastebin.com/Sg2vQnAH
I'm currently having the same issues, using etterna 0.68.1 package from the aur

**Comment by richardjharris** [comment]
Same here, using 0.68.1 compiled from source on Ubuntu 19.10.

**Comment by firmart** [comment]
Same issue. 
Etterna  0.68.1
OpenSSL 1.1.1b
Ubuntu 19.04

**Comment by Francesco149** [comment]
same here, built from source on void linux

latest git etterna
libressl-3.0.2
libcurl-7.69

**Comment by Francesco149** [comment]
well this is really weird. I tried debugging it so I rebuilt with -g3 and the crash was gone and I could log in. so I tried rebuilding with the default compiler flags and it's still not crashing anymore and I have no idea how to repro the crash again. should've saved the gdb backtrace for the non-debug build... it didn't have line numbers but it at least had func names

**Comment by poco0317** [comment]
Retry with the latest release.

**Comment by poco0317** [comment]
No activity

**Comment by nico-abram** [comment]
@Francesco149 @firmart @ridho9 @richardjharris @izik1 @and-sha 

If the issue still happens you can mention it here. If it *doesn't* happen, some confirmation would be nice

**Comment by ridho9** [comment]
Just finished rebuilt from git, as far as I see it is working now

**Comment by BeyondMagic** [comment]
Happening in last build of AUR, I'm on Manjaro 5.8.18-1. Going to try the git package.

**Comment by mid-kid** [comment]
Happens on etterna-0.70.4, built from git with default options:
```
Thread 1 "Etterna" received signal SIGBUS, Bus error.
0x0000555555d947fc in PointsToValidCall(void const*) ()
(gdb) bt
#0  0x0000555555d947fc in PointsToValidCall(void const*) ()
#1  0x0000555555d94b91 in do_backtrace(void const**, unsigned long, BacktraceContext const*) ()
#2  0x0000555555d94ce7 in GetBacktrace(void const**, unsigned long, BacktraceContext const*) ()
#3  0x0000555555d95f57 in CrashHandler::ForceCrash(char const*) ()
#4  0x00005555557b741d in sm_crash(char const*) ()
#5  0x0000555555d90ac8 in __assert_fail ()
#6  0x0000555555beadae in rapidjson::GenericValue<rapidjson::UTF8<char>, rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator> >::MemberEnd() const ()
#7  0x0000555555be1aa9 in rapidjson::GenericValue<rapidjson::UTF8<char>, rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator> >::HasMember(char const*) const ()
#8  0x0000555555d34766 in DownloadManager::RefreshTop25(Skillset)::{lambda(HTTPRequest&, CURLMsg*)#1}::operator()(HTTPRequest&, CURLMsg*) const ()
#9  0x0000555555d3fd59 in void std::__invoke_impl<void, DownloadManager::RefreshTop25(Skillset)::{lambda(HTTPRequest&, CURLMsg*)#1}&, HTTPRequest&, CURLMsg*>(std::__invoke_other, DownloadManager::RefreshTop25(Skillset)::{lambda(HTTPRequest&, CURLMsg*)#1}&, HTTPRequest&, CURLMsg*&&) ()
#10 0x0000555555d3de28 in std::enable_if<is_invocable_r_v<void, DownloadManager::RefreshTop25(Skillset)::{lambda(HTTPRequest&, CURLMsg*)#1}&, HTTPRequest&, CURLMsg*>, void>::type std::__invoke_r<void, DownloadManager::RefreshTop25(Skillset)::{lambda(HTTPRequest&, CURLMsg*)#1}&, HTTPRequest&, CURLMsg*>(DownloadManager::RefreshTop25(Skillset)::{lambda(HTTPRequest&, CURLMsg*)#1}&, HTTPRequest&, CURLMsg*&&) ()
#11 0x0000555555d3b157 in std::_Function_handler<void (HTTPRequest&, CURLMsg*), DownloadManager::RefreshTop25(Skillset)::{lambda(HTTPRequest&, CURLMsg*)#1}>::_M_invoke(std::_Any_data const&, HTTPRequest&, CURLMsg*&&) ()
#12 0x0000555555d4acbb in std::function<void (HTTPRequest&, CURLMsg*)>::operator()(HTTPRequest&, CURLMsg*) const ()
#13 0x0000555555d2f173 in DownloadManager::SendRequestToURL(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::vector<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > >, std::function<void (HTTPRequest&, CURLMsg*)>, bool, bool, bool, bool)::{lambda(HTTPRequest&, CURLMsg*)#1}::operator()(HTTPRequest&, CURLMsg*) const ()
#14 0x0000555555d3f2d7 in void std::__invoke_impl<void, DownloadManager::SendRequestToURL(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::vector<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > >, std::function<void (HTTPRequest&, CURLMsg*)>, bool, bool, bool, bool)::{lambda(HTTPRequest&, CURLMsg*)#1}&, HTTPRequest&, CURLMsg*>(std::__invoke_other, DownloadManager::SendRequestToURL(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::vector<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > >, std::function<void (HTTPRequest&, CURLMsg*)>, bool, bool, bool, bool)::{lambda(HTTPRequest&, CURLMsg*)#1}&, HTTPRequest&, CURLMsg*&&) ()
#15 0x0000555555d3cb73 in std::enable_if<is_invocable_r_v<void, DownloadManager::SendRequestToURL(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::vector<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > >, std::function<void (HTTPRequest&, CURLMsg*)>, bool, bool, bool, bool)::{lambda(HTTPRequest&, CURLMsg*)#1}&, HTTPRequest&, CURLMsg*>, void>::type std::__invoke_r<void, DownloadManager::SendRequestToURL(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::vector<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > >, std::function<void (HTTPRequest&, CURLMsg*)>, bool, bool, bool, bool)::{lambda(HTTPRequest&, CURLMsg*)#1}&, HTTPRequest&, CURLMsg*>(DownloadManager::SendRequestToURL(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::vector<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > >, std::function<void (HTTPRequest&, CURLMsg*)>, bool, bool, bool, bool)::{lambda(HTTPRequest&, CURLMsg*)#1}&, HTTPRequest&, CURLMsg*&&) ()
#16 0x0000555555d3a53f in std::_Function_handler<void (HTTPRequest&, CURLMsg*), DownloadManager::SendRequestToURL(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::vector<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > >, std::function<void (HTTPRequest&, CURLMsg*)>, bool, bool, bool, bool)::{lambda(HTTPRequest&, CURLMsg*)#1}>::_M_invoke(std::_Any_data const&, HTTPRequest&, CURLMsg*&&) ()
#17 0x0000555555d4acbb in std::function<void (HTTPRequest&, CURLMsg*)>::operator()(HTTPRequest&, CURLMsg*) const ()
#18 0x0000555555d28d49 in DownloadManager::UpdateHTTP(float) ()
#19 0x0000555555d28956 in DownloadManager::Update(float) ()
#20 0x00005555557b5a34 in GameLoop::RunGameLoop() ()
```

Doesn't seem to happen anymore on the develop branch (commit a5c4f72d3079ec402e980c5e4831f540b9f1d893). I wonder what fixed it...

**Comment by mid-kid** [comment]
Apparently commit eb058ff3d696da85ab9f75abe031a3b9b55b4564 seems to fix it
